/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package classes;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Otavio Augusto
 */
public class ListarVeiculos extends javax.swing.JInternalFrame {
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form ListarVeiculos
     */
    public ListarVeiculos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        comboBoxVeiculos = new javax.swing.JComboBox<>();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(650, 356));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)), "Veículos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(320, 602));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Chassi", "Placa", "Marca", "Modelo", "Revendedor", "End. Revendedor", "Tel. Revendedor", "Velocidade Máx.", "Qtd. Passageiros", "Carga Máx."
            }
        ));
        jScrollPane1.setViewportView(tabela);

        btnListar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        comboBoxVeiculos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Passeio", "Carga" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboBoxVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        modelo = (DefaultTableModel) tabela.getModel();
        modelo.setRowCount(0);
        
        if (comboBoxVeiculos.getSelectedItem().equals("Passeio")) {
            for (int i = 0; i < VeiculoPasseio.vetPasseio.size(); i++) { 
                modelo.addRow(new Object[]{ //criando um array de objetos e adicionando este vetor na linha do modelo
                    VeiculoPasseio.vetPasseio.get(i).getChassi(),
                    VeiculoPasseio.vetPasseio.get(i).getPlaca(),
                    VeiculoPasseio.vetPasseio.get(i).getMarca(),
                    VeiculoPasseio.vetPasseio.get(i).getModelo(),
                    VeiculoPasseio.vetPasseio.get(i).getRevendedor(),
                    VeiculoPasseio.vetPasseio.get(i).getEndRevendedor(),
                    VeiculoPasseio.vetPasseio.get(i).getTelRevendedor(),
                    VeiculoPasseio.vetPasseio.get(i).getVelMaxima(),
                    VeiculoPasseio.vetPasseio.get(i).getQtdPassageiros(),
                    ("---")
                });
            }
        }
        
        if (comboBoxVeiculos.getSelectedItem().equals("Carga")) {
            for (int i = 0; i < VeiculoCarga.vetCarga.size(); i++) { 
                modelo.addRow(new Object[]{ //criando um array de objetos e adicionando este vetor na linha do modelo
                    VeiculoCarga.vetCarga.get(i).getChassi(),
                    VeiculoCarga.vetCarga.get(i).getPlaca(),
                    VeiculoCarga.vetCarga.get(i).getMarca(),
                    VeiculoCarga.vetCarga.get(i).getModelo(),
                    VeiculoCarga.vetCarga.get(i).getRevendedor(),
                    VeiculoCarga.vetCarga.get(i).getEndRevendedor(),
                    VeiculoCarga.vetCarga.get(i).getTelRevendedor(),
                    ("---"),
                    ("---"),
                    VeiculoCarga.vetCarga.get(i).getCargMaxima()
                });
            }
        } 
        
        if (comboBoxVeiculos.getSelectedItem().equals("Selecione...")){
            JOptionPane.showConfirmDialog(null, 
                "Selecione uma opção!", "AVISO!",
                JOptionPane.YES_OPTION);
        }
    }//GEN-LAST:event_btnListarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar;
    private javax.swing.JComboBox<String> comboBoxVeiculos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
